### ISSUE TITLE
Agents crashing on load.

### ISSUE THREAD

**Issue by forensec** [s3inlc/hashtopussy-agent#12]
Hi,

I've had success with dictionary attacks. When I'm trying brute forcing, or rules or masks upon load I get this error:

Client Version 0.43.13
Checking for client updates
You are using the latest client version
System is Windows
Existing token found
Logged in to server
Hashcat version v3.6.0 found
Getting task
Downloading hashlist for this task, please wait...
Getting chunk...
Server has requested the client to measure the keyspace for this task
Something went wrong with keyspace measuring

Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToInt64(String value)
   at hashtopussy.hashcatClass.parseKeyspace(String line, Int64& keySpace)
   at hashtopussy.hashcatClass.runKeyspace(Int64& keySpace)
   at hashtopussy.taskClass.getChunk(Int32 inTask)
   at hashtopussy.taskClass.getTask()
   at hashtopussy.Program.Main(String[] args)

I've tried various commands. The last command tried, which still gave that error was simply:
-a 3 #HL#

Any help would be appreciated.

**Comment by blazer2x** [comment]
-a 3 is bruteforce
Can you try
#HL# -a 3 ?d?d?d?d?d?d?d?d
That should do a digit bruteforce len8 digits

**Comment by forensec** [comment]
That's working great now. 
Is that bruteforcing for passwords only of 8 characters?

**Comment by blazer2x** [comment]
For more information please refer to the hashcat documentation.
But some built-in charsets you can use are

    ?l = abcdefghijklmnopqrstuvwxyz
    ?u = ABCDEFGHIJKLMNOPQRSTUVWXYZ
    ?d = 0123456789
    ?s = «space»!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    ?a = ?l?u?d?s
    ?b = 0x00 - 0xff

You can also use custom ones.
